{"variants":[{"paths":["\/documentation\/securedefaults"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/securedefaults"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SecureDefaults","title":"SecureDefaults","symbolKind":"module","role":"collection","modules":[{"name":"SecureDefaults"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults":{"role":"collection","title":"SecureDefaults","abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaultsVersionNumber":{"role":"symbol","title":"SecureDefaultsVersionNumber","fragments":[{"kind":"identifier","text":"SecureDefaultsVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaultsVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaultsversionnumber"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaultsVersionString":{"role":"symbol","title":"SecureDefaultsVersionString","fragments":[{"kind":"identifier","text":"SecureDefaultsVersionString"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaultsVersionString","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaultsversionstring"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults":{"role":"symbol","title":"SecureDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecureDefaults"}],"abstract":[{"type":"text","text":"Overrides the "},{"type":"codeVoice","code":"NSUserDefaults"},{"type":"text","text":" class within addition to encrypt and decrypt data. It uses the"},{"type":"text","text":" "},{"type":"text","text":"Advanced Encryption Standard (AES) to encrypt and decrypt data."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecureDefaults"}],"url":"\/documentation\/securedefaults\/securedefaults"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaultsVersionNumber","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaultsVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/title","value":"PVSecureDefaults"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/fragments","value":[{"kind":"identifier","text":"PVSecureDefaults"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}