{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(PVSecureDefaults) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecureDefaults"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/securedefaults\/securedefaults"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/securedefaults\/securedefaults"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/objc(cs)NSUserDefaults"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/objc(pl)NSObject","doc:\/\/org.cocoapods.SecureDefaults\/s7CVarArgP","doc:\/\/org.cocoapods.SecureDefaults\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SecureDefaults\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SecureDefaults\/SQ","doc:\/\/org.cocoapods.SecureDefaults\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Overrides the "},{"type":"codeVoice","code":"NSUserDefaults"},{"type":"text","text":" class within addition to encrypt and decrypt data. It uses the"},{"type":"text","text":" "},{"type":"text","text":"Advanced Encryption Standard (AES) to encrypt and decrypt data."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecureDefaults"}],"title":"SecureDefaults","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SecureDefaults@objc(cs)PVSecureDefaults","modules":[{"name":"SecureDefaults"}],"navigatorTitle":[{"kind":"identifier","text":"SecureDefaults"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/init(suiteName:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/IV","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/isKeyCreated","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/key","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/keychainAccessGroup","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/keychainAccessible","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/password"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/array(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/bool(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/data(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/dictionary(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/double(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/float(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/integer(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/object(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/rawObject(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-2c6ez","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-40846","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-61p3z","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-838wi","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-9dcas","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-kt5j","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/setRawObject(_:forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/string(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/stringArray(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/url(forKey:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/shared"]}],"references":{"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/bool(forKey:)":{"role":"symbol","title":"bool(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bool"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/bool(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"boolForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/bool(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecureDefaults","preciseIdentifier":"c:@M@SecureDefaults@objc(cs)PVSecureDefaults"}],"abstract":[{"type":"text","text":"Use this instead of "},{"type":"codeVoice","code":"NSUserDefaults.standard"}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/shared","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/shared"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/string(forKey:)":{"role":"symbol","title":"string(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/string(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/string(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/rawObject(forKey:)":{"role":"symbol","title":"rawObject(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/rawObject(forKey:)","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/rawobject(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/dictionary(forKey:)":{"role":"symbol","title":"dictionary(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dictionary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/dictionary(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dictionaryForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/dictionary(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/keychainAccessGroup":{"role":"symbol","title":"keychainAccessGroup","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAccessGroup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A key whose value is a string indicating the access group an item is in."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/keychainAccessGroup","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/keychainaccessgroup"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/set(_:forKey:)-kt5j":{"role":"symbol","title":"set(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-kt5j","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBool:forKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-kt5j"},"doc://org.cocoapods.SecureDefaults/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SecureDefaults\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SecureDefaults/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SecureDefaults\/SQ"},"doc://org.cocoapods.SecureDefaults/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SecureDefaults\/SH"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/object(forKey:)":{"role":"symbol","title":"object(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"object"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/object(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"objectForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/object(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/init(suiteName:)":{"role":"symbol","title":"init(suiteName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"suiteName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/init(suiteName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSuiteName:"}],"url":"\/documentation\/securedefaults\/securedefaults\/init(suitename:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/set(_:forKey:)-9dcas":{"role":"symbol","title":"set(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-9dcas","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDouble:forKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-9dcas"},"doc://org.cocoapods.SecureDefaults/objc(cs)NSUserDefaults":{"type":"unresolvable","title":"NSUserDefaults","identifier":"doc:\/\/org.cocoapods.SecureDefaults\/objc(cs)NSUserDefaults"},"doc://org.cocoapods.SecureDefaults/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SecureDefaults\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/set(_:forKey:)-40846":{"role":"symbol","title":"set(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-40846","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setInteger:forKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-40846"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/stringArray(forKey:)":{"role":"symbol","title":"stringArray(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringArray"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/stringArray(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringArrayForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/stringarray(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/url(forKey:)":{"role":"symbol","title":"url(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/url(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"URLForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/url(forkey:)"},"doc://org.cocoapods.SecureDefaults/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SecureDefaults\/s7CVarArgP"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/keychainAccessible":{"role":"symbol","title":"keychainAccessible","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keychainAccessible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A key whose value indicates when a keychain item is accessible."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/keychainAccessible","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/keychainaccessible"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/key":{"role":"symbol","title":"key","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"key"},{"type":"text","text":" to use within encrypting and decrypting. The key is regenerated for each "},{"type":"codeVoice","code":"suitName"},{"type":"text","text":" and stored"},{"type":"text","text":" "},{"type":"text","text":"in Keychain as (Keys.AESKey)-(suitename)."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/key","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/key"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/isKeyCreated":{"role":"symbol","title":"isKeyCreated","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isKeyCreated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this property to check that password is already created for this particular defaults."},{"type":"text","text":" "},{"type":"text","text":"It can be useful if you share user defaults and keychain groups. Or just to ensure that you set a"},{"type":"text","text":" "},{"type":"text","text":"password only once."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/isKeyCreated","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/iskeycreated"},"doc://org.cocoapods.SecureDefaults/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SecureDefaults\/objc(pl)NSObject"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/set(_:forKey:)-838wi":{"role":"symbol","title":"set(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-838wi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setFloat:forKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-838wi"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/set(_:forKey:)-2c6ez":{"role":"symbol","title":"set(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-2c6ez","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setObject:forKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-2c6ez"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/float(forKey:)":{"role":"symbol","title":"float(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"float"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/float(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floatForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/float(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/double(forKey:)":{"role":"symbol","title":"double(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"double"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/double(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"doubleForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/double(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/data(forKey:)":{"role":"symbol","title":"data(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/data(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/data(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/password":{"role":"symbol","title":"password","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A password to build a key if the one isn’t set manually by "},{"type":"codeVoice","code":"key"},{"type":"text","text":" property"}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/password","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/password"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/set(_:forKey:)-61p3z":{"role":"symbol","title":"set(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-61p3z","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setURL:forKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-61p3z"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/integer(forKey:)":{"role":"symbol","title":"integer(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"integer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/integer(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"integerForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/integer(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults":{"role":"symbol","title":"SecureDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecureDefaults"}],"abstract":[{"type":"text","text":"Overrides the "},{"type":"codeVoice","code":"NSUserDefaults"},{"type":"text","text":" class within addition to encrypt and decrypt data. It uses the"},{"type":"text","text":" "},{"type":"text","text":"Advanced Encryption Standard (AES) to encrypt and decrypt data."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecureDefaults"}],"url":"\/documentation\/securedefaults\/securedefaults"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults":{"role":"collection","title":"SecureDefaults","abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/array(forKey:)":{"role":"symbol","title":"array(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"array"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/array(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"arrayForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/array(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/IV":{"role":"symbol","title":"IV","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IV"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"IV"},{"type":"text","text":" to use within encrypting and decrypting. The key is regenerated for each "},{"type":"codeVoice","code":"suitName"},{"type":"text","text":" and stored"},{"type":"text","text":" "},{"type":"text","text":"in Keychain as (Keys.AESIV)-(suitename)."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/IV","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/iv"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/setRawObject(_:forKey:)":{"role":"symbol","title":"setRawObject(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRawObject"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/setRawObject(_:forKey:)","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults\/securedefaults\/setrawobject(_:forkey:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PVSecureDefaults"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PVSecureDefaults"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PVSecureDefaults"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/array(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/bool(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/data(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/dictionary(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/double(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/float(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/init(suiteName:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/integer(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/object(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-2c6ez","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-40846","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-61p3z","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-838wi","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-9dcas","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-kt5j","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/string(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/stringArray(forKey:)","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/url(forKey:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SecureDefaults\/objc(cs)NSUserDefaults"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PVSecureDefaults"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSUserDefaults","preciseIdentifier":"c:objc(cs)NSUserDefaults"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1bool(forKey:)\/title","value":"boolForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1bool(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"boolForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1string(forKey:)\/title","value":"stringForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1string(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1dictionary(forKey:)\/title","value":"dictionaryForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1dictionary(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dictionaryForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-kt5j\/title","value":"setBool:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-kt5j\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBool:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1object(forKey:)\/title","value":"objectForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1object(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"objectForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1init(suiteName:)\/title","value":"initWithSuiteName:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1init(suiteName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSuiteName:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-9dcas\/title","value":"setDouble:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-9dcas\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDouble:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-40846\/title","value":"setInteger:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-40846\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setInteger:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1stringArray(forKey:)\/title","value":"stringArrayForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1stringArray(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stringArrayForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1url(forKey:)\/title","value":"URLForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1url(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-838wi\/title","value":"setFloat:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-838wi\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFloat:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-2c6ez\/title","value":"setObject:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-2c6ez\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setObject:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1float(forKey:)\/title","value":"floatForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1float(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1double(forKey:)\/title","value":"doubleForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1double(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"doubleForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1data(forKey:)\/title","value":"dataForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1data(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-61p3z\/title","value":"setURL:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-61p3z\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setURL:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1integer(forKey:)\/title","value":"integerForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1integer(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"integerForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/title","value":"PVSecureDefaults"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/fragments","value":[{"kind":"identifier","text":"PVSecureDefaults"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1array(forKey:)\/title","value":"arrayForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1array(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"arrayForKey:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}