{"variants":[{"paths":["\/documentation\/swiftdate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftdate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DOTNETFormatter","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DOTNETParser","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/ISOFormatter","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/ISOParser","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/RelativeFormatter","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriod","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodChain","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodCollection","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodGroup"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/CalendarConvertible","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateParsable","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateRepresentable","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateToStringTrasformable","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/LocaleConvertible","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/StringToDateTransformable","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodProtocol","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/ZoneConvertible"]},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateFormats","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateInRegion","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Region","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SwiftDate","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimeCalculationOptions","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Year"]},{"title":"Operators","identifiers":["doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-40ign","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-55fcr","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-5qmxs","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-5rw9v","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-9t8w1","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-2en16","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-6q4gi","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-8oanw","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-9qbx7","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-9wyvw","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/==(_:_:)","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/_(_:_:)-3mkpi","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/_(_:_:)-4d5fy","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/_=(_:_:)-5fqfx","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/_=(_:_:)-80n7z"]},{"title":"Type Aliases","identifiers":["doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Calendars"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateComparisonType","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateRelatedType","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateToStringStyles","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/ISO8601ParserError","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/IntervalType","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Locales","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Month","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/RelativeFormatterLanguage","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/RoundDateMode","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SortMode","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SortType","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/StringToDateStyles","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SymbolFormatStyle","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodAnchor","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodRelation","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/WeekDay","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Zones"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SwiftDate","title":"SwiftDate","symbolKind":"module","role":"collection","modules":[{"name":"SwiftDate"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/_(_:_:)-3mkpi":{"role":"symbol","title":"<(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"<"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/_(_:_:)-3mkpi","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/_(_:_:)-3mkpi"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/RelativeFormatter":{"role":"symbol","title":"RelativeFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RelativeFormatter"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/RelativeFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RelativeFormatter"}],"url":"\/documentation\/swiftdate\/relativeformatter"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/ISO8601ParserError":{"role":"symbol","title":"ISO8601ParserError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISO8601ParserError"}],"abstract":[{"type":"text","text":"This defines all possible errors you can encounter parsing ISO8601 string"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/ISO8601ParserError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ISO8601ParserError"}],"url":"\/documentation\/swiftdate\/iso8601parsererror"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/ISOParser":{"role":"symbol","title":"ISOParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISOParser"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/ISOParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ISOParser"}],"url":"\/documentation\/swiftdate\/isoparser"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/-(_:_:)-8oanw":{"role":"symbol","title":"-(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"-"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateComponents","preciseIdentifier":"s:10Foundation14DateComponentsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[{"type":"text","text":"Subtracts date components from a date and returns a new date."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-8oanw","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/-(_:_:)-8oanw"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/-(_:_:)-6q4gi":{"role":"symbol","title":"-(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"-"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateComponents","preciseIdentifier":"s:10Foundation14DateComponentsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-6q4gi","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/-(_:_:)-6q4gi"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/RoundDateMode":{"role":"symbol","title":"RoundDateMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundDateMode"}],"abstract":[{"type":"text","text":"Rounding mode for dates."},{"type":"text","text":" "},{"type":"text","text":"Round off\/up (ceil) or down (floor) target date."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/RoundDateMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RoundDateMode"}],"url":"\/documentation\/swiftdate\/rounddatemode"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/+(_:_:)-55fcr":{"role":"symbol","title":"+(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"+"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-55fcr","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/+(_:_:)-55fcr"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/ZoneConvertible":{"role":"symbol","title":"ZoneConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZoneConvertible"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/ZoneConvertible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZoneConvertible"}],"url":"\/documentation\/swiftdate\/zoneconvertible"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/SortMode":{"role":"symbol","title":"SortMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SortMode"}],"abstract":[{"type":"text","text":"Sort type"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SortMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SortMode"}],"url":"\/documentation\/swiftdate\/sortmode"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/Calendars":{"role":"symbol","title":"Calendars","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Calendars"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Calendars","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Calendars"}],"url":"\/documentation\/swiftdate\/calendars"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/TimePeriodAnchor":{"role":"symbol","title":"TimePeriodAnchor","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimePeriodAnchor"}],"abstract":[{"type":"text","text":"When a time periods is lengthened or shortened, it does so anchoring one date"},{"type":"text","text":" "},{"type":"text","text":"of the time period and then changing the other one. There is also an option to"},{"type":"text","text":" "},{"type":"text","text":"anchor the centerpoint of the time period, changing both the start and end dates."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimePeriodAnchor"}],"url":"\/documentation\/swiftdate\/timeperiodanchor"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/Locales":{"role":"symbol","title":"Locales","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Locales"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Locales","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Locales"}],"url":"\/documentation\/swiftdate\/locales"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DateParsable":{"role":"symbol","title":"DateParsable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateParsable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateParsable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DateParsable"}],"url":"\/documentation\/swiftdate\/dateparsable"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/IntervalType":{"role":"symbol","title":"IntervalType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalType"}],"abstract":[{"type":"text","text":"Whether the time period is Open or Closed"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/IntervalType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalType"}],"url":"\/documentation\/swiftdate\/intervaltype"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/+(_:_:)-9t8w1":{"role":"symbol","title":"+(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"+"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateComponents","preciseIdentifier":"s:10Foundation14DateComponentsV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[{"type":"text","text":"Adds date components to a date and returns a new date."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-9t8w1","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/+(_:_:)-9t8w1"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/-(_:_:)-2en16":{"role":"symbol","title":"-(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"-"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-2en16","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/-(_:_:)-2en16"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/StringToDateTransformable":{"role":"symbol","title":"StringToDateTransformable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StringToDateTransformable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/StringToDateTransformable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StringToDateTransformable"}],"url":"\/documentation\/swiftdate\/stringtodatetransformable"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DateRepresentable":{"role":"symbol","title":"DateRepresentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateRepresentable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateRepresentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DateRepresentable"}],"url":"\/documentation\/swiftdate\/daterepresentable"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate":{"role":"collection","title":"SwiftDate","abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DateRelatedType":{"role":"symbol","title":"DateRelatedType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateRelatedType"}],"abstract":[{"type":"text","text":"Related type enum to get derivated date from a receiver date."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateRelatedType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DateRelatedType"}],"url":"\/documentation\/swiftdate\/daterelatedtype"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/==(_:_:)":{"role":"symbol","title":"==(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/==(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/==(_:_:)"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/TimePeriodGroup":{"role":"symbol","title":"TimePeriodGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimePeriodGroup"}],"abstract":[{"type":"text","text":"Time period groups are the final abstraction of date and time in DateTools."},{"type":"text","text":" "},{"type":"text","text":"Here, time periods are gathered and organized into something useful."},{"type":"text","text":" "},{"type":"text","text":"There are two main types of time period groups, "},{"type":"codeVoice","code":"TimePeriodCollection"},{"type":"text","text":" and "},{"type":"codeVoice","code":"TimePeriodChain"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimePeriodGroup"}],"url":"\/documentation\/swiftdate\/timeperiodgroup"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/Region":{"role":"symbol","title":"Region","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Region"}],"abstract":[{"type":"text","text":"Region define a context both for "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" and "},{"type":"codeVoice","code":"DateInRegion"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Each "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" is assigned to the currently set `SwiftDate.default"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Region","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Region"}],"url":"\/documentation\/swiftdate\/region"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/StringToDateStyles":{"role":"symbol","title":"StringToDateStyles","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StringToDateStyles"}],"abstract":[{"type":"text","text":"String to date transform"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/StringToDateStyles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StringToDateStyles"}],"url":"\/documentation\/swiftdate\/stringtodatestyles"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/SymbolFormatStyle":{"role":"symbol","title":"SymbolFormatStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SymbolFormatStyle"}],"abstract":[{"type":"text","text":"Style used to format month, weekday, quarter symbols."},{"type":"text","text":" "},{"type":"text","text":"Stand-alone properties are for use in places like calendar headers."},{"type":"text","text":" "},{"type":"text","text":"Non-stand-alone properties are for use in context (for example, “Saturday, November 12th”)."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SymbolFormatStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SymbolFormatStyle"}],"url":"\/documentation\/swiftdate\/symbolformatstyle"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/-(_:_:)-9wyvw":{"role":"symbol","title":"-(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"-"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", ["},{"kind":"typeIdentifier","text":"Calendar","preciseIdentifier":"s:10Foundation8CalendarV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Component","preciseIdentifier":"s:10Foundation8CalendarV9ComponentO"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-9wyvw","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/-(_:_:)-9wyvw"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/_=(_:_:)-5fqfx":{"role":"symbol","title":">=(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":">="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/_=(_:_:)-5fqfx","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/_=(_:_:)-5fqfx"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/Zones":{"role":"symbol","title":"Zones","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zones"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Zones","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Zones"}],"url":"\/documentation\/swiftdate\/zones"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/_=(_:_:)-80n7z":{"role":"symbol","title":"<=(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"<="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/_=(_:_:)-80n7z","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/_=(_:_:)-80n7z"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/TimePeriodChain":{"role":"symbol","title":"TimePeriodChain","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimePeriodChain"}],"abstract":[{"type":"text","text":"Time period chains serve as a tightly coupled set of time periods."},{"type":"text","text":" "},{"type":"text","text":"They are always organized by start and end date, and have their own characteristics like"},{"type":"text","text":" "},{"type":"text","text":"a StartDate and EndDate that are extrapolated from the time periods within."},{"type":"text","text":" "},{"type":"text","text":"Time period chains do not allow overlaps within their set of time periods."},{"type":"text","text":" "},{"type":"text","text":"This type of group is ideal for modeling schedules like sequential meetings or appointments."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodChain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimePeriodChain"}],"url":"\/documentation\/swiftdate\/timeperiodchain"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/TimeCalculationOptions":{"role":"symbol","title":"TimeCalculationOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimeCalculationOptions"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimeCalculationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimeCalculationOptions"}],"url":"\/documentation\/swiftdate\/timecalculationoptions"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/Year":{"role":"symbol","title":"Year","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Year"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Year","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Year"}],"url":"\/documentation\/swiftdate\/year"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/WeekDay":{"role":"symbol","title":"WeekDay","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WeekDay"}],"abstract":[{"type":"text","text":"This define the weekdays for some functions."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/WeekDay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WeekDay"}],"url":"\/documentation\/swiftdate\/weekday"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/+(_:_:)-5rw9v":{"role":"symbol","title":"+(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"+"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateComponents","preciseIdentifier":"s:10Foundation14DateComponentsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-5rw9v","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/+(_:_:)-5rw9v"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/ISOFormatter":{"role":"symbol","title":"ISOFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISOFormatter"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/ISOFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ISOFormatter"}],"url":"\/documentation\/swiftdate\/isoformatter"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/SwiftDateVersionNumber":{"role":"symbol","title":"SwiftDateVersionNumber","fragments":[{"kind":"identifier","text":"SwiftDateVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SwiftDateVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/swiftdateversionnumber"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/RelativeFormatterLanguage":{"role":"symbol","title":"RelativeFormatterLanguage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RelativeFormatterLanguage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/RelativeFormatterLanguage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RelativeFormatterLanguage"}],"url":"\/documentation\/swiftdate\/relativeformatterlanguage"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DOTNETFormatter":{"role":"symbol","title":"DOTNETFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNETFormatter"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DOTNETFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNETFormatter"}],"url":"\/documentation\/swiftdate\/dotnetformatter"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/TimePeriodCollection":{"role":"symbol","title":"TimePeriodCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimePeriodCollection"}],"abstract":[{"type":"text","text":"Time period collections serve as loose sets of time periods."},{"type":"text","text":" "},{"type":"text","text":"They are unorganized unless you decide to sort them, and have their own characteristics"},{"type":"text","text":" "},{"type":"text","text":"like a "},{"type":"codeVoice","code":"start"},{"type":"text","text":" and "},{"type":"codeVoice","code":"end"},{"type":"text","text":" that are extrapolated from the time periods within."},{"type":"text","text":" "},{"type":"text","text":"Time period collections allow overlaps within their set of time periods."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodCollection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimePeriodCollection"}],"url":"\/documentation\/swiftdate\/timeperiodcollection"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/CalendarConvertible":{"role":"symbol","title":"CalendarConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalendarConvertible"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/CalendarConvertible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CalendarConvertible"}],"url":"\/documentation\/swiftdate\/calendarconvertible"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/-(_:_:)-9qbx7":{"role":"symbol","title":"-(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"-"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DateComponents","preciseIdentifier":"s:10Foundation14DateComponentsV"}],"abstract":[{"type":"text","text":"Subtracts two dates and returns the relative components from "},{"type":"codeVoice","code":"lhs"},{"type":"text","text":" to "},{"type":"codeVoice","code":"rhs"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Follows this mathematical pattern:"},{"type":"text","text":" "},{"type":"text","text":"let difference = lhs - rhs"},{"type":"text","text":" "},{"type":"text","text":"rhs + difference = lhs"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/-(_:_:)-9qbx7","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/-(_:_:)-9qbx7"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/SortType":{"role":"symbol","title":"SortType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SortType"}],"abstract":[{"type":"text","text":"Sorting type"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SortType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SortType"}],"url":"\/documentation\/swiftdate\/sorttype"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DateComparisonType":{"role":"symbol","title":"DateComparisonType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateComparisonType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateComparisonType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DateComparisonType"}],"url":"\/documentation\/swiftdate\/datecomparisontype"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DateToStringStyles":{"role":"symbol","title":"DateToStringStyles","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateToStringStyles"}],"abstract":[{"type":"text","text":"Format to represent a date to string"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateToStringStyles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DateToStringStyles"}],"url":"\/documentation\/swiftdate\/datetostringstyles"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DateToStringTrasformable":{"role":"symbol","title":"DateToStringTrasformable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateToStringTrasformable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateToStringTrasformable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DateToStringTrasformable"}],"url":"\/documentation\/swiftdate\/datetostringtrasformable"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/TimePeriodProtocol":{"role":"symbol","title":"TimePeriodProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimePeriodProtocol"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimePeriodProtocol"}],"url":"\/documentation\/swiftdate\/timeperiodprotocol"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/+(_:_:)-40ign":{"role":"symbol","title":"+(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"+"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateComponents","preciseIdentifier":"s:10Foundation14DateComponentsV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"abstract":[{"type":"text","text":"Adds date components to a date and returns a new date."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-40ign","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/+(_:_:)-40ign"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/LocaleConvertible":{"role":"symbol","title":"LocaleConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocaleConvertible"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/LocaleConvertible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocaleConvertible"}],"url":"\/documentation\/swiftdate\/localeconvertible"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DateInRegion":{"role":"symbol","title":"DateInRegion","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateInRegion"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateInRegion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DateInRegion"}],"url":"\/documentation\/swiftdate\/dateinregion"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/TimePeriod":{"role":"symbol","title":"TimePeriod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimePeriod"}],"abstract":[{"type":"text","text":"Time periods are represented by the TimePeriodProtocol protocol."},{"type":"text","text":" "},{"type":"text","text":"Required variables and method impleementations are bound below."},{"type":"text","text":" "},{"type":"text","text":"An inheritable implementation of the TimePeriodProtocol is available through the TimePeriod class."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimePeriod"}],"url":"\/documentation\/swiftdate\/timeperiod"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DateFormats":{"role":"symbol","title":"DateFormats","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateFormats"}],"abstract":[{"type":"text","text":"Encapsulate the logic to use date format strings"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DateFormats","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DateFormats"}],"url":"\/documentation\/swiftdate\/dateformats"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/DOTNETParser":{"role":"symbol","title":"DOTNETParser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNETParser"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/DOTNETParser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNETParser"}],"url":"\/documentation\/swiftdate\/dotnetparser"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/TimePeriodRelation":{"role":"symbol","title":"TimePeriodRelation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimePeriodRelation"}],"abstract":[{"type":"text","text":"There may come a need, say when you are making a scheduling app, when"},{"type":"text","text":" "},{"type":"text","text":"it might be good to know how two time periods relate to one another"},{"type":"text","text":" "},{"type":"text","text":"Are they the same? Is one inside of another?"},{"type":"text","text":" "},{"type":"text","text":"All these questions may be asked using the relationship method of TimePeriod."}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/TimePeriodRelation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimePeriodRelation"}],"url":"\/documentation\/swiftdate\/timeperiodrelation"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/Month":{"role":"symbol","title":"Month","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Month"}],"abstract":[{"type":"text","text":"Defines months in a year"}],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/Month","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Month"}],"url":"\/documentation\/swiftdate\/month"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/SwiftDateVersionString":{"role":"symbol","title":"SwiftDateVersionString","fragments":[{"kind":"identifier","text":"SwiftDateVersionString"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SwiftDateVersionString","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/swiftdateversionstring"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/_(_:_:)-4d5fy":{"role":"symbol","title":">(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":">"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/_(_:_:)-4d5fy","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/_(_:_:)-4d5fy"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/SwiftDate":{"role":"symbol","title":"SwiftDate","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftDate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SwiftDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwiftDate"}],"url":"\/documentation\/swiftdate\/swiftdate"},"doc://org.cocoapods.SwiftDate/documentation/SwiftDate/+(_:_:)-5qmxs":{"role":"symbol","title":"+(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"+"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"},{"kind":"text","text":", ["},{"kind":"typeIdentifier","text":"Calendar","preciseIdentifier":"s:10Foundation8CalendarV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Component","preciseIdentifier":"s:10Foundation8CalendarV9ComponentO"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"DateInRegion","preciseIdentifier":"s:9SwiftDate0B8InRegionV"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/+(_:_:)-5qmxs","kind":"symbol","type":"topic","url":"\/documentation\/swiftdate\/+(_:_:)-5qmxs"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SwiftDateVersionNumber","doc:\/\/org.cocoapods.SwiftDate\/documentation\/SwiftDate\/SwiftDateVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}