{"variants":[{"paths":["\/documentation\/swiftyrsa"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/swiftyrsa"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/ClearMessage-swift.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/EncryptedMessage-swift.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/PrivateKey-swift.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/PublicKey-swift.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Signature-swift.class"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Key","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Message"]},{"title":"Type Aliases","identifiers":["doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Padding"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/SwiftyRSA","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/SwiftyRSAError"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SwiftyRSA","title":"SwiftyRSA","symbolKind":"module","role":"collection","modules":[{"name":"SwiftyRSA"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/Padding":{"role":"symbol","title":"Padding","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Padding"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Padding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Padding"}],"url":"\/documentation\/swiftyrsa\/padding"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/Signature-swift.class":{"role":"symbol","title":"Signature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Signature"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Signature-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Signature"}],"url":"\/documentation\/swiftyrsa\/signature-swift.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/Signature-c.class":{"role":"symbol","title":"Signature","fragments":[{"kind":"identifier","text":"Signature"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Signature-c.class","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/signature-c.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/Key":{"role":"symbol","title":"Key","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Key"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Key","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Key"}],"url":"\/documentation\/swiftyrsa\/key"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/ClearMessage-c.class":{"role":"symbol","title":"ClearMessage","fragments":[{"kind":"identifier","text":"ClearMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/ClearMessage-c.class","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/clearmessage-c.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/SwiftyRSAError":{"role":"symbol","title":"SwiftyRSAError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftyRSAError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/SwiftyRSAError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwiftyRSAError"}],"url":"\/documentation\/swiftyrsa\/swiftyrsaerror"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/PublicKey-swift.class":{"role":"symbol","title":"PublicKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicKey"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/PublicKey-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PublicKey"}],"url":"\/documentation\/swiftyrsa\/publickey-swift.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/EncryptedMessage-swift.class":{"role":"symbol","title":"EncryptedMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncryptedMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/EncryptedMessage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EncryptedMessage"}],"url":"\/documentation\/swiftyrsa\/encryptedmessage-swift.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/PublicKey-c.class":{"role":"symbol","title":"PublicKey","fragments":[{"kind":"identifier","text":"PublicKey"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/PublicKey-c.class","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/publickey-c.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/SwiftyRSAVersionNumber":{"role":"symbol","title":"SwiftyRSAVersionNumber","fragments":[{"kind":"identifier","text":"SwiftyRSAVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for SwiftyRSA."}],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/SwiftyRSAVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/swiftyrsaversionnumber"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/Message":{"role":"symbol","title":"Message","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Message"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Message","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Message"}],"url":"\/documentation\/swiftyrsa\/message"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/SwiftyRSA":{"role":"symbol","title":"SwiftyRSA","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SwiftyRSA"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/SwiftyRSA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SwiftyRSA"}],"url":"\/documentation\/swiftyrsa\/swiftyrsa"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/VerificationResult":{"role":"symbol","title":"VerificationResult","fragments":[{"kind":"identifier","text":"VerificationResult"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/VerificationResult","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/verificationresult"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/SwiftyRSAVersionString":{"role":"symbol","title":"SwiftyRSAVersionString","fragments":[{"kind":"identifier","text":"SwiftyRSAVersionString"}],"abstract":[{"type":"text","text":"Project version string for SwiftyRSA."}],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/SwiftyRSAVersionString","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/swiftyrsaversionstring"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA":{"role":"collection","title":"SwiftyRSA","abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/ClearMessage-swift.class":{"role":"symbol","title":"ClearMessage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClearMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/ClearMessage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClearMessage"}],"url":"\/documentation\/swiftyrsa\/clearmessage-swift.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/DigestType":{"role":"symbol","title":"DigestType","fragments":[{"kind":"identifier","text":"DigestType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/DigestType","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/digesttype"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/EncryptedMessage-c.class":{"role":"symbol","title":"EncryptedMessage","fragments":[{"kind":"identifier","text":"EncryptedMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/EncryptedMessage-c.class","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/encryptedmessage-c.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/PrivateKey-swift.class":{"role":"symbol","title":"PrivateKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivateKey"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/PrivateKey-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivateKey"}],"url":"\/documentation\/swiftyrsa\/privatekey-swift.class"},"doc://org.cocoapods.SwiftyRSA/documentation/SwiftyRSA/PrivateKey-c.class":{"role":"symbol","title":"PrivateKey","fragments":[{"kind":"identifier","text":"PrivateKey"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/PrivateKey-c.class","kind":"symbol","type":"topic","url":"\/documentation\/swiftyrsa\/privatekey-c.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/ClearMessage-c.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/EncryptedMessage-c.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/PrivateKey-c.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/PublicKey-c.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/Signature-c.class","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/VerificationResult"]},{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/SwiftyRSAVersionNumber","doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/SwiftyRSAVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.SwiftyRSA\/documentation\/SwiftyRSA\/DigestType"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}