{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"float"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"defaultName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/securedefaults\/securedefaults\/float(forkey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/securedefaults\/securedefaults\/float(forkey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/float(forKey:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"float"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"float(forKey:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SecureDefaults@objc(cs)PVSecureDefaults(im)floatForKey:","modules":[{"name":"SecureDefaults"}],"navigatorTitle":[{"kind":"identifier","text":"floatForKey:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults"]]},"references":{"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/float(forKey:)":{"role":"symbol","title":"float(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"float"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/float(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"floatForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/float(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults":{"role":"symbol","title":"SecureDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecureDefaults"}],"abstract":[{"type":"text","text":"Overrides the "},{"type":"codeVoice","code":"NSUserDefaults"},{"type":"text","text":" class within addition to encrypt and decrypt data. It uses the"},{"type":"text","text":" "},{"type":"text","text":"Advanced Encryption Standard (AES) to encrypt and decrypt data."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecureDefaults"}],"url":"\/documentation\/securedefaults\/securedefaults"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults":{"role":"collection","title":"SecureDefaults","abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"floatForKey:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatForKey:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"identifier","text":"floatForKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"defaultName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1float(forKey:)\/title","value":"floatForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1float(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"floatForKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/title","value":"PVSecureDefaults"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/fragments","value":[{"kind":"identifier","text":"PVSecureDefaults"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}