{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"suiteName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"suitename"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/securedefaults\/securedefaults\/init(suitename:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/securedefaults\/securedefaults\/init(suitename:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/init(suiteName:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"suiteName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(suiteName:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SecureDefaults@objc(cs)PVSecureDefaults(im)initWithSuiteName:","modules":[{"name":"SecureDefaults"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSuiteName:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults"]]},"references":{"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults":{"role":"collection","title":"SecureDefaults","abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults":{"role":"symbol","title":"SecureDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecureDefaults"}],"abstract":[{"type":"text","text":"Overrides the "},{"type":"codeVoice","code":"NSUserDefaults"},{"type":"text","text":" class within addition to encrypt and decrypt data. It uses the"},{"type":"text","text":" "},{"type":"text","text":"Advanced Encryption Standard (AES) to encrypt and decrypt data."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecureDefaults"}],"url":"\/documentation\/securedefaults\/securedefaults"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/init(suiteName:)":{"role":"symbol","title":"init(suiteName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"suiteName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/init(suiteName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSuiteName:"}],"url":"\/documentation\/securedefaults\/securedefaults\/init(suitename:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSuiteName:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSuiteName:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSuiteName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"suitename"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/title","value":"PVSecureDefaults"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/fragments","value":[{"kind":"identifier","text":"PVSecureDefaults"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1init(suiteName:)\/title","value":"initWithSuiteName:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1init(suiteName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSuiteName:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}