{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"integer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"defaultName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/securedefaults\/securedefaults\/integer(forkey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/securedefaults\/securedefaults\/integer(forkey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/integer(forKey:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"integer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"integer(forKey:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SecureDefaults@objc(cs)PVSecureDefaults(im)integerForKey:","modules":[{"name":"SecureDefaults"}],"navigatorTitle":[{"kind":"identifier","text":"integerForKey:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults"]]},"references":{"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults":{"role":"symbol","title":"SecureDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecureDefaults"}],"abstract":[{"type":"text","text":"Overrides the "},{"type":"codeVoice","code":"NSUserDefaults"},{"type":"text","text":" class within addition to encrypt and decrypt data. It uses the"},{"type":"text","text":" "},{"type":"text","text":"Advanced Encryption Standard (AES) to encrypt and decrypt data."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecureDefaults"}],"url":"\/documentation\/securedefaults\/securedefaults"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/integer(forKey:)":{"role":"symbol","title":"integer(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"integer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/integer(forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"integerForKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/integer(forkey:)"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults":{"role":"collection","title":"SecureDefaults","abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"integerForKey:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"integerForKey:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"integerForKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"defaultName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/title","value":"PVSecureDefaults"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/fragments","value":[{"kind":"identifier","text":"PVSecureDefaults"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1integer(forKey:)\/title","value":"integerForKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1integer(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"integerForKey:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}