{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"defaultName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-40846"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-40846"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-40846","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"set(_:forKey:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SecureDefaults@objc(cs)PVSecureDefaults(im)setInteger:forKey:","modules":[{"name":"SecureDefaults"}],"navigatorTitle":[{"kind":"identifier","text":"setInteger:forKey:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults"]]},"references":{"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults/set(_:forKey:)-40846":{"role":"symbol","title":"set(_:forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults\/set(_:forKey:)-40846","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setInteger:forKey:"}],"url":"\/documentation\/securedefaults\/securedefaults\/set(_:forkey:)-40846"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults":{"role":"collection","title":"SecureDefaults","abstract":[],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults","kind":"symbol","type":"topic","url":"\/documentation\/securedefaults"},"doc://org.cocoapods.SecureDefaults/documentation/SecureDefaults/SecureDefaults":{"role":"symbol","title":"SecureDefaults","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecureDefaults"}],"abstract":[{"type":"text","text":"Overrides the "},{"type":"codeVoice","code":"NSUserDefaults"},{"type":"text","text":" class within addition to encrypt and decrypt data. It uses the"},{"type":"text","text":" "},{"type":"text","text":"Advanced Encryption Standard (AES) to encrypt and decrypt data."}],"identifier":"doc:\/\/org.cocoapods.SecureDefaults\/documentation\/SecureDefaults\/SecureDefaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SecureDefaults"}],"url":"\/documentation\/securedefaults\/securedefaults"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setInteger:forKey:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setInteger:forKey:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setInteger:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"forKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"defaultName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-40846\/title","value":"setInteger:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults~1set(_:forKey:)-40846\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setInteger:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/title","value":"PVSecureDefaults"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SecureDefaults~1documentation~1SecureDefaults~1SecureDefaults\/fragments","value":[{"kind":"identifier","text":"PVSecureDefaults"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}